name: Build and Publish Python Package
on:
  push:
    tags:
      - 'v*'  # Run when "v*" version tags are created like "v1.0.0"
jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: github.repository == 'mozilla-iam/mozilla-aws-cli'  # Only deploy from mozilla-iam not from forks
    steps:
      - name: Install build dependencies
        run: python3 -m pip install --upgrade wheel setuptools
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build package
        run: python3 setup.py sdist bdist_wheel --universal
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          # password: ${{ secrets.TEST_PYPI_TOKEN }}
          # repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TOKEN }}
